INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('FLOWER_UP', TRUE);
INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('BROWS_LIGHT', TRUE);
INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('NANO_WIRES', TRUE);
INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('CLEAN_SKIN', TRUE);
INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('BROWS_THERAPY', TRUE);
INSERT INTO TIPO_FICHA (nome, ativo) VALUES ('REALIGN_BROWS', TRUE);

/*INSERT INTO USUARIO (CPF,LOGIN,NOME,SENHA, ROLE) VALUES ('60373280300', 'JUDUARTE', 'JULIANA DUARTE', 'Juh1Duarte2', 1);*/

INSERT INTO ROLE (NOME) VALUES ('ADMIN');
INSERT INTO ROLE (NOME) VALUES ('BASIC');